# Defines a GitRepository resource to fetch configuration from a Git repository
apiVersion: source.toolkit.fluxcd.io/v1beta2 # API version of the GitRepository resource
kind: GitRepository # Specifies the kind of resource
metadata:
  name: my-git-repo # Name of the GitRepository resource
  namespace: flux-system # Namespace where this resource resides
spec:
  interval: 1m0s # Interval at which the repository will be fetched
  url: https://github.com/example/repo.git # URL of the Git repository
  branch: main # Branch to fetch
  secretRef:
    name: git-credentials # Reference to a Kubernetes secret for authentication
