# Defines a HelmRepository resource to fetch Helm charts
apiVersion: source.toolkit.fluxcd.io/v1beta2 # API version of the HelmRepository resource
kind: HelmRepository # Specifies the kind of resource
metadata:
  name: bitnami-repo # Name of the HelmRepository resource
  namespace: flux-system # Namespace where this resource resides
spec:
  interval: 1h0m # Interval at which the repository will be refreshed
  url: https://charts.bitnami.com/bitnami # URL of the Helm chart repository
