# Defines a HelmRelease resource to deploy applications using Helm charts
apiVersion: helm.toolkit.fluxcd.io/v2beta1 # API version of the HelmRelease resource
kind: HelmRelease # Specifies the kind of resource
metadata:
  name: my-app-release # Name of the HelmRelease resource
  namespace: my-app-namespace # Namespace where this resource resides
spec:
  releaseName: my-app # Name of the Helm release
  interval: 5m0s # Interval at which the release will be reconciled
  chart:
    spec:
      chart: my-app-chart # Name of the Helm chart
      version: 1.2.3 # Version of the Helm chart
      sourceRef:
        kind: HelmRepository # Type of source (HelmRepository)
        name: bitnami-repo # Name of the HelmRepository resource
  values: # Custom values for the Helm chart
    replicaCount: 3 # Number of replicas
    image:
      repository: my-app # Repository for the application image
      tag: latest # Tag of the application image
