#
# flux HelmRelase crd for installing nginx ingress controller helm chart
#
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: nginx
  namespace: nginx
spec:
  chart:
    spec:
      chart: nginx-ingress
      version: 1.2.x
      interval: 5h # check for new version every 5 hours
      sourceRef:
        kind: HelmRepository
        name: nginx
  releaseName: nginx
  interval: 1h # reconcile every 1 hour
