# #
# # flux HelmRelase crd for installing nginx ingress controller helm chart
# #
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: prometheus-stack
  namespace: monitoring
spec:
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 67.4.0
      interval: 5h # check for new version every 5 hours
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
  releaseName: kube-prometheus-stack
  interval: 1h # reconcile every 1 hour
