#
# flux HelmRelase crd for installing nginx ingress controller helm chart
#
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: prometheus-stack
  namespace: monitoring
spec:
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 67.3.X
      interval: 5h # check for new version every 5 hours
      sourceRef:
        kind: HelmRepository
        name: kube-prometheus-stack
  releaseName: prometheus-stack
  interval: 1h # reconcile every 1 hour
