# Defines a HelmRepository resource to fetch Helm charts
apiVersion: source.toolkit.fluxcd.io/v1beta2 # API version of the HelmRepository resource
kind: HelmRepository # Specifies the kind of resource
metadata:
  name: prometheus-community # Name of the HelmRepository resource
  namespace: monitoring # Namespace where this resource resides
spec:
  interval: 1h0m # Interval at which the repository will be refreshed
  url: https://prometheus-community.github.io/helm-charts # URL of the Helm chart repository
